# Copyright (c) 2025 Martin R. Raumann
# SPDX-License-Identifier: BSD-3-Clause
"""
SAM E51 game builder

Generates:
- Individual C array files for each game (_data.c)
- game_registry.c with menu entries
"""

from pathlib import Path
from typing import List, Dict
from . import common


def build_game_array(game: Dict, z3_path: Path, output_c_path: Path):
    """
    Generate C array file for SAM E51

    Args:
        game: Game dictionary from registry
        z3_path: Path to .z3 game file
        output_c_path: Path to output .c file
    """
    data = common.z3_to_bytes(z3_path)
    info = common.get_z3_info(data)
    array_name = common.sanitize_identifier(game['id'])

    with open(output_c_path, 'w') as f:
        # Header comment
        f.write(f"/*\n")
        f.write(f" * Generated story data from {z3_path.name}\n")
        f.write(f" * Game: {game['name']}\n")
        f.write(f" * File size: {len(data)} bytes\n")
        f.write(f" * Release: {info['release']}, Serial: {info['serial']}\n")
        f.write(f" * Generated by: game_builder/same51.py\n")
        f.write(f" */\n\n")

        # Includes
        f.write("#include <stdint.h>\n")
        f.write("#include <stddef.h>\n\n")

        # Array definition
        f.write(f"/* Story data array - stored in flash memory */\n")
        f.write(f"const uint8_t {array_name}_data[] = {{\n")

        # Write data as hex bytes, 16 per line
        formatted = common.format_bytes_per_line(data, bytes_per_line=16, indent="    ")
        f.write(formatted)

        f.write("\n};\n\n")

        # Size constant
        f.write(f"const size_t {array_name}_size = sizeof({array_name}_data);\n")

    print(f"[ok] Generated {output_c_path.name} ({len(data)} bytes)")


def build_registry(games: List[Dict], output_c_path: Path):
    """
    Generate game_registry.c for SAM E51 multi-game menu

    Args:
        games: List of game dictionaries from registry
        output_c_path: Path to output game_registry.c
    """
    with open(output_c_path, 'w') as f:
        # Header comment
        f.write("/*\n")
        f.write(" * Auto-generated game registry for SAM E51\n")
        f.write(f" * Games: {len(games)}\n")
        f.write(" * Generated by: game_builder/same51.py\n")
        f.write(" */\n\n")

        # Includes
        f.write("#include <stdint.h>\n")
        f.write("#include <stddef.h>\n\n")

        # Extern declarations for game data
        for game in games:
            array_name = common.sanitize_identifier(game['id'])
            f.write(f"extern const uint8_t {array_name}_data[];\n")

        f.write("\n")

        # Registry structure definition (use typedef to match game_registry.h)
        f.write("/* Game registry entry structure (matches game_registry.h) */\n")
        f.write("typedef struct {\n")
        f.write("    const char *name;          /* Display name for menu */\n")
        f.write("    const uint8_t *data;       /* Pointer to game data */\n")
        f.write("    size_t size;                /* Size of game data */\n")
        f.write("} game_entry_t;\n\n")

        # Registry array (use name expected by firmware)
        f.write("/* Game registry - array of available games */\n")
        f.write("const game_entry_t games[] = {\n")

        for game in games:
            array_name = common.sanitize_identifier(game['id'])
            # Escape quotes in game name
            display_name = game['name'].replace('"', '\\"')
            # Use actual size literal, not variable (required for const initializer)
            game_size = game['size']
            f.write(f'    {{"{display_name}", {array_name}_data, {game_size}}},\n')

        f.write("};\n\n")

        # Count constant (matches game_registry.h)
        f.write(f"const int num_games = {len(games)};\n")

    print(f"[ok] Generated {output_c_path.name} ({len(games)} games)")


def build_same51(registry: Dict, output_dir: Path):
    """
    Build multi-game system for SAM E51

    Generates:
    - <game_id>_data.c for each enabled game
    - game_registry.c with menu entries

    Args:
        registry: Game registry dictionary
        output_dir: Output directory for generated C files
    """
    games = common.get_downloaded_games('same51', registry)

    print(f"Building {len(games)} games for SAM E51...\n")

    # Generate individual game data files
    generated_games = []
    for game in games:
        z3_path = common.CATALOG_DIR / game['filename']
        array_name = common.sanitize_identifier(game['id'])
        output_c_path = output_dir / f"{array_name}_data.c"
        build_game_array(game, z3_path, output_c_path)
        generated_games.append(game)

    # Generate registry file
    print()
    registry_path = output_dir / "game_registry.c"
    build_registry(generated_games, registry_path)

    # Summary
    print(f"\n[ok] SAM E51 build complete")
    print(f"  Games: {len(generated_games)}")
    print(f"  Output directory: {output_dir}")
    print(f"\nGenerated files:")
    for game in generated_games:
        array_name = common.sanitize_identifier(game['id'])
        print(f"  - {array_name}_data.c")
    print(f"  - game_registry.c")
